#!/bin/bash
set -euxo pipefail

HOSTNAME=worker8

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --fail http://server:8001/api
do
    echo "$HOSTNAME waiting for server"
    sleep 1
done

# install k3s
TOKEN=$(ssh -o StrictHostKeyChecking=no server cat /var/lib/rancher/k3s/server/node-token)
VERSION=v1.29.0+k3s1
curl -sfL https://get.k3s.io | K3S_URL=https://server:6443 K3S_TOKEN=$TOKEN INSTALL_K3S_VERSION=$VERSION sh -

echo "$HOSTNAME connected to server"
